### ISSUE TITLE
Release date of the demo and code

### ISSUE THREAD

**Issue by HrsPythonix** [hzxie/CityDreamer#1]
Great work! Wondering when you plan to release your demo on hugging face and the code to play with.

**Comment by fakerybakery** [comment]
Is there any update on this @hzxie? Do you have an estimate of how long it usually takes for a paper to be accepted?

**Comment by cnsystem** [comment]
+1

**Comment by fakerybakery** [comment]
Hi,
This project looks really cool. If the paper hasn't been accepted yet, would you consider potentially releasing the code early?
Thanks!

**Comment by hzxie** [comment]
Hi all. The hugging face demo is online available: https://huggingface.co/spaces/hzxie/city-dreamer
The source code is planned to be public by the end of this month.

**Comment by fakerybakery** [comment]
Thank you! 	Unfortunately, the license on the HF Space is not open sourced because it is NC-only. Are there any plans to switch to an open source license?
Thanks!

**Comment by hzxie** [comment]
@fakerybakery 
No. The funding for this project does not permit us to license it for commercial use.

**Comment by fakerybakery** [comment]
Makes sense! Thanks for releasing!
