### ISSUE TITLE
Approximate release time of training code 

### ISSUE THREAD

**Issue by Deaddawn** [hzxie/CityDreamer#10]
Hi, happen to see your wonderful work! Wondering is there an approximate release time of training code?

**Comment by hzxie** [comment]
I am currently involved in another research project. 
I plan to release the training code after the CVPR conference, but I cannot guarantee it.

Please stay tuned!

**Comment by KAKAKA-521** [comment]
Are there any plans to release train code these days?
Can't wait to train custom data! 
Thanks!

**Comment by hzxie** [comment]
Maybe after the CVPR conference.

**Comment by chl916185** [comment]
How can I download the dataset?
@hzxie

**Comment by hzxie** [comment]
The training code has been released.
