### ISSUE TITLE
arch_list[-1] += '+PTX'

### ISSUE THREAD

**Issue by dastan1910** [hzxie/CityDreamer#11]
arch_list[-1] += '+PTX'
      IndexError: list index out of range
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for extrude_tensor
  Running setup.py clean for extrude_tensor
Failed to build extrude_tensor
ERROR: Could not build wheels for extrude_tensor, which is required to install pyproject.toml-based projects

error when your install bash
```
cd $CITY_DREAMER_HOME/extensions
for e in `ls -d */`
do
  cd $CITY_DREAMER_HOME/extensions/$e
  pip install .
done
```

**Comment by hzxie** [comment]
Refer to this: https://discuss.pytorch.org/t/pytorch-extension-issue/161042/3
If the problem still exists, please provide your CUDA and NVIDIA driver versions.

**Comment by kwtk86** [comment]
problem fixed
