### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/city-dreamer/output/sampler.pth'

### ISSUE THREAD

**Issue by dastan1910** [hzxie/CityDreamer#12]
FileNotFoundError: [Errno 2] No such file or directory: '/home/city-dreamer/output/sampler.pth'

When can I get this file?

**Comment by chl916185** [comment]
How can I download it?
@dastan1910

**Comment by hzxie** [comment]
@chl916185 Did you read README?
