### ISSUE TITLE
 It seems like the pre-trained models and datasets cannot be downloaded.

### ISSUE THREAD

**Issue by zsgsyl** [hzxie/CityDreamer#15]
It seems like the pre-trained models and datasets cannot be downloaded. 404 not found

**Comment by hzxie** [comment]
I cannot reproduce your error. Please provide more information.

**Comment by chl916185** [comment]
@zsgsyl 
How do I download the dataset?

**Comment by hzxie** [comment]
@chl916185 
Refer to #3

**Comment by chl916185** [comment]
After following the above operations, the email did not receive the message? Can you send an email to my mailbox?
My email address is chenhongzijing@163.com
@hzxie
