### ISSUE TITLE
codec_id=27, error: Encoder not found

### ISSUE THREAD

**Issue by kuaiqushangzixiba** [hzxie/CityDreamer#16]
demo.py
![image](https://github.com/hzxie/CityDreamer/assets/42159103/e0a3e35c-fffa-43a8-9622-2c09e85f7026)
![image](https://github.com/hzxie/CityDreamer/assets/42159103/770b5917-6ef5-409d-8edb-d73428969564)

inference.py
![image](https://github.com/hzxie/CityDreamer/assets/42159103/39609d50-4074-4381-9fc5-2588aa64473b)

**Comment by hzxie** [comment]
**demo.py**

You should change the trajectory to make sure all the points of the trajectory are inside the city layout image.

**inference.py**

Please refer to https://stackoverflow.com/questions/70247344/save-video-in-opencv-with-h264-codec

If you are using Anaconda, please use the following commands

```
conda install -c conda-forge ffmpeg
conda install -c conda-forge opencv
```

**Comment by Monad-Cube** [comment]
I have change the video format and fix the problem.
`def get_video(frames, output_file):
    video = cv2.VideoWriter(
        output_file,
        cv2.VideoWriter_fourcc(*"mp4v"), # change avc1 to mp4v
        4,
        (CONSTANTS["GES_IMAGE_WIDTH"], CONSTANTS["GES_IMAGE_HEIGHT"]),
    )
    for f in frames:
        video.write(f)

    video.release()`
