### ISSUE TITLE
The output is video, can export the building structure,mesh obj  or other formats...

### ISSUE THREAD

**Issue by kuaiqushangzixiba** [hzxie/CityDreamer#17]
The output is video, can export the building structure,mesh obj  or other formats...

**Comment by hzxie** [comment]
You can use COLMAP to reconstruct 3D meshes from the generated video.

**Comment by kuaiqushangzixiba** [comment]
Ok, so citydreamer is actually a photo, but from all angles, can I understand it this way, is it similar to 3dgs?

**Comment by hzxie** [comment]
Yes. 3D-GS is an explicit representation, while CityDreamer uses an implicit representation NeRF.

**Comment by kuaiqushangzixiba** [comment]
How do the video sequence consists of 600 frames with a resolution of
960×540, I took the osm data provided and generated a video of only 6 seconds

**Comment by hzxie** [comment]
Change this value to `600`

https://github.com/hzxie/CityDreamer/blob/49a0d9e05908861fdda2cf4d73ef32ac4309d553/scripts/inference.py#L58
