### ISSUE TITLE
Why the hf.png in the OSM dataset is empty?

### ISSUE THREAD

**Issue by NikkiElwin** [hzxie/CityDreamer#18]
Hi, I downloaded the OSM dataset in your shared link, but I found that the hf.png is different from Figure.3 (a).

![hf](https://github.com/hzxie/CityDreamer/assets/59132156/b8b74687-93a1-4365-9222-9b472df8253e)

**Comment by hzxie** [comment]
It is not empty. It is a 16-bit PNG image. You can visualize it with `matplotlib`.
