### ISSUE TITLE
ERROR: Failed building wheel for grid_encoder

### ISSUE THREAD

**Issue by CeciliaYWei** [hzxie/CityDreamer#21]
Hi,

thanks a lot for sharing this amazing project.
Following the README file, I successfully installed extrude_tensor and voxrender, but unfortunately the wheel for grid_encoder fails to be built all the time. Could you please provide me some solutions?
My environment is: Ubuntu 24.04, CUDA 12.2, Python 3.8.19, PyTorch 2.3.1.

Best,
Cecilia

**Comment by hzxie** [comment]
Please provide more error logs.
