### ISSUE TITLE
Question about the FOCAL_LEN ?

### ISSUE THREAD

**Issue by whiteinblue** [hzxie/CityDreamer#22]
In file of cam_pose_generator.py, the formula of computing focal len is：
" FOCAL_LEN = (IMG_SIZE[0] / 2 / np.tan(np.deg2rad(GES_VFOV))) * 2.06", my question is why you multiply 2.06 ？

**Comment by hzxie** [comment]
2.06 is the MAGIC NUMBER to make it aligned with Google Earth Renderings. Otherwise, the OSM and GoogleEarth cannot be aligned.

https://github.com/hzxie/CityDreamer/blob/fe85dab57e12e6689878023c0908d37e8e02b5c2/scripts/dataset_generator.py#L580-L581
