### ISSUE TITLE
Resolution of Generated Layouts

### ISSUE THREAD

**Issue by djFatNerd** [hzxie/CityDreamer#24]
Hi, in your **Dataset** section you mentioned the resolution of the layout dataset is approximately 0.597 meters per pixel, and in the **Implementation Details** section you also mentioned the data was compressed by a factor of 16. Does that indicate in the generated layout, one pixel actually stands for 0.597 * 16 =  9.552 meters ?

**Comment by hzxie** [comment]
No. Each pixel is approximately 0.597 meters. 
The height fields and semantic fields are compressed by a factor of 16 in the **VQVAE's codebook**.
