### ISSUE TITLE
Weights download link failed

### ISSUE THREAD

**Issue by lxy198** [hzxie/CityDreamer#7]
Thank you for your open source!

There's a problem here:
Weight download link not available
![D610E975-DE59-4360-AC67-1C279D2DBD49](https://github.com/hzxie/CityDreamer/assets/107126081/d872d6d2-985d-49ad-8221-d9b482cd2fda)

**Comment by chaoer** [comment]
waiting for an answer

**Comment by hzxie** [comment]
Fixed. Sorry for the inconvenience.
