### ISSUE TITLE
web engine export

### ISSUE THREAD

**Issue by Scoutink** [hzxie/CityDreamer#8]
Apologies for the too many questions below, but this is perfect for the project I am working on (and I feel our project will perfectly demonstrate the potentials of your work here):

Is it possible to export this to web 3d engines like BabylonJS? And if yes, will I be able to split one 3d map to many zones (for loading/unloading optimization) and will it be easy to apply collision on it?

**Comment by hzxie** [comment]
Sorry, I am not familiar with Web 3D engines. Theoretically, the 3D map can be split into multiple zones.
